// Pool de cartes du mode "Draft aux packs" — calibré sur l'historique compétitif réel.
// Échelle impitoyable : 90+ réservé aux performances historiques majeures.

export const RARITIES = ['Commune', 'Rare', 'Épique', 'Légendaire', 'WANTED'];

// Probabilités de tirage par emplacement de carte dans un pack (en %).
export const RARITY_WEIGHTS = {
  Commune: 633,
  Rare: 290,
  'Épique': 40,
  'Légendaire': 10,
  WANTED : 3
};

export const RARITY_COLORS = {
  Commune: '#8b9bb4',
  Rare: '#00e5ff',
  'Épique': '#ff3366',
  'Légendaire': '#ffd700',
  WANTED: '#ffffff'
};

export const CARD_POOL = [
  // ==========================================
  // --- TOPLANE ---
  // ==========================================
  {
    "id": "edg_zdz",
    "baseName": "zdz",
    "variant": "EDG zdz",
    "role": "Top",
    "rating": 68,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/EDG_zdz.webp",
    "nationality": "CN",
    "teamTag": "EDG",
    "league": "LPL"
  },
  {
    "id": "t1-zeus",
    "baseName": "Zeus",
    "variant": "T1 Zeus",
    "role": "Top",
    "rating": 83,
    "rarity": "Rare",
    "image": "/cardsImg/others/T1_zeus.png",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "hle-zeus",
    "baseName": "Zeus",
    "variant": "HLE Zeus",
    "role": "Top",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/hle_zeus.webp",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "zeus-lck",
    "baseName": "Zeus",
    "variant": "LCK champ Zeus",
    "role": "Top",
    "rating": 85,
    "rarity": "Épique",
    "image": "/cardsImg/others/zeus_lck_2022.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "zeus-mvp-msi",
    "baseName": "Zeus",
    "variant": "2026 MSI MVP",
    "role": "Top",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/MSI_MVP_zeus.jpg",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "zeus-mvp-2023",
    "baseName": "Zeus",
    "variant": "T1 legend",
    "role": "Top",
    "rating": 94,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/T1_legend_zeus.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "NAVI-adam",
    "baseName": "Adam",
    "variant": "NAVI Adam",
    "role": "Top",
    "rating": 69,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/NAVI_adam.webp",
    "nationality": "FR",
    "teamTag": "NAVI",
    "league": "LEC"
  },
  {
    "id": "blg-bin",
    "baseName": "Bin",
    "variant": "BLG Bin",
    "role": "Top",
    "rating": 83,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/BLG_bin.webp",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "bin-FirstStand-2026",
    "baseName": "Bin",
    "variant": "First Stand MVP Bin",
    "role": "Top",
    "rating": 89,
    "rarity": "Épique",
    "image": "/cardsImg/others/BLG-Bin-FST.jpg",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "bin-lpl-mvp",
    "baseName": "Bin",
    "variant": "2x LPL Finals MVP",
    "role": "Top",
    "rating": 93,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/BLG_bin.jpg",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "szygenda",
    "baseName": "Szygenda",
    "variant": "Szygenda",
    "role": "Top",
    "rating": 51,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/szygenda.webp",
    "nationality": "DK",
    "teamTag": "RGE",
    "league": "LEC"
  },
  {
    "id": "tes-369",
    "baseName": "369",
    "variant": "TES 369",
    "role": "Top",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/TES_369.webp",
    "nationality": "CN",
    "teamTag": "TES",
    "league": "LPL"
  },
  {
    "id": "369-lpl-champion",
    "baseName": "369",
    "variant": "2023 MSI Champion",
    "role": "Top",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/msi_jdg_369.jpg",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "bro-morgan",
    "baseName": "Morgan",
    "variant": "BRO Morgan",
    "role": "Top",
    "rating": 63,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/BRO_morgan.webp",
    "nationality": "KR",
    "teamTag": "BRO",
    "league": "LCK"
  },
  {
    "id": "gen-kiin",
    "baseName": "Kiin",
    "variant": "Gen.G Kiin",
    "role": "Top",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/GENG_kiin.webp",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "kiin-lck-mvp",
    "baseName": "Kiin",
    "variant": "LCK Finals MVP",
    "role": "Top",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/geng_kiin_lck.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "gx-odoamne",
    "baseName": "Odoamne",
    "variant": "GX Odoamne",
    "role": "Top",
    "rating": 66,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/GX_odoamne.webp",
    "nationality": "RO",
    "teamTag": "GX",
    "league": "LEC"
  },
  {
    "id": "brokenblade-g2",
    "baseName": "BrokenBlade",
    "variant": "G2 BrokenBlade",
    "role": "Top",
    "rating": 80,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/g2_brokenblade.webp",
    "nationality": "DE",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "NAVI-maynter",
    "baseName": "Maynter",
    "variant": "NAVI Maynter",
    "role": "Top",
    "rating": 62,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/NAVI_maynter.webp",
    "nationality": "UA",
    "teamTag": "NAVI",
    "league": "LEC"
  },
  {
    "id": "fnc-oscarinin",
    "baseName": "Oscarinin",
    "variant": "FNC Oscarinin",
    "role": "Top",
    "rating": 75,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/FNC_oscarinin.webp",
    "nationality": "ES",
    "teamTag": "FNC",
    "league": "LEC"
  },
  {
    "id": "sen-impact",
    "baseName": "Impact",
    "variant": "SEN Impact",
    "role": "Top",
    "rating": 70,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/SEN_impact.webp",
    "nationality": "KR",
    "teamTag": "SEN",
    "league": "LCS"
  },
  {
    "id": "fly-bwipo",
    "baseName": "Bwipo",
    "variant": "FLY Bwipo",
    "role": "Top",
    "rating": 76,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/FLY_bwipo.webp",
    "nationality": "BE",
    "teamTag": "FLY",
    "league": "LCS"
  },
  {
    "id": "dns-dudu",
    "baseName": "DuDu",
    "variant": "DNS DuDu",
    "role": "Top",
    "rating": 61,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DNS_dudu.webp",
    "nationality": "KR",
    "teamTag": "DNS",
    "league": "LCK"
  },
  {
    "id": "t1-doran",
    "baseName": "Doran",
    "variant": "T1 Doran",
    "role": "Top",
    "rating": 78,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/T1_doran.webp",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "doran-lck-champ",
    "baseName": "Doran",
    "variant": "LCK Champion Doran",
    "role": "Top",
    "rating": 84,
    "rarity": "Épique",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "sk-wunder",
    "baseName": "Wunder",
    "variant": "SK Wunder",
    "role": "Top",
    "rating": 67,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/SK_wunder.webp",
    "nationality": "DK",
    "teamTag": "SK",
    "league": "LEC"
  },
  {
    "id": "g2-wunder-2019",
    "baseName": "Wunder",
    "variant": "G2 Wunder",
    "role": "Top",
    "rating": 79,
    "rarity": "Rare",
    "image": "/cardsImg/others/G2_wunder.png",
    "nationality": "DK",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "theshy-legend",
    "baseName": "TheShy",
    "variant": "Legend",
    "role": "Top",
    "rating": 97,
    "rarity": "WANTED",
    "image": "/cardsImg/others/TheShy_legend.jpg",
    "nationality": "KR",
    "teamTag": "IG",
    "league": "LPL"
  },

  // ==========================================
  // --- JUNGLE ---
  // ==========================================
  {
    "id": "bro-gideon",
    "baseName": "Gideon",
    "variant": "BRO Gideon",
    "role": "Jungle",
    "rating": 64,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/BRO_gideon.webp",
    "nationality": "KR",
    "teamTag": "BRO",
    "league": "LCK"
  },
  {
    "id": "gen-canyon",
    "baseName": "Canyon",
    "variant": "Gen.G Canyon",
    "role": "Jungle",
    "rating": 83,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/GENG_canyon.webp",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "canyon-ewc",
    "baseName": "Canyon",
    "variant": "EWC 2025 Champion",
    "role": "Jungle",
    "rating": 89,
    "rarity": "Épique",
    "image": "/cardsImg/others/GenG_Canyon.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "canyon-lck-champion",
    "baseName": "Canyon",
    "variant": "5x LCK champion",
    "role": "Jungle",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/LCK_geng_canyon.jpg",
    "nationality": "KR",
    "teamTag": "DK",
    "league": "LCK"
  },
  {
    "id": "canyon-mvp-2020",
    "baseName": "Canyon",
    "variant": "Worlds MVP",
    "role": "Jungle",
    "rating": 96,
    "rarity": "WANTED",
    "image": "/cardsImg/others/DWG_canyon_WORLDS.jpeg",
    "nationality": "KR",
    "teamTag": "DWG",
    "league": "LCK"
  },
  {
    "id": "gx-isma",
    "baseName": "Isma",
    "variant": "GX Isma",
    "role": "Jungle",
    "rating": 65,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/GX_isma.webp",
    "nationality": "FR",
    "teamTag": "GX",
    "league": "LEC"
  },
  {
    "id": "jdg-kanavi",
    "baseName": "Kanavi",
    "variant": "JDG Kanavi",
    "role": "Jungle",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/others/JDG_kanavi.png",
    "nationality": "KR",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "kanavi-msi-2023",
    "baseName": "Kanavi",
    "variant": "MSI Champion Kanavi",
    "role": "Jungle",
    "rating": 89,
    "rarity": "Épique",
    "nationality": "KR",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "kanavi-lpl-mvp",
    "baseName": "Kanavi",
    "variant": "LPL MVP",
    "role": "Jungle",
    "rating": 91,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/JDG_kanavi.jpg",
    "nationality": "KR",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "painter-t1-2026-sub",
    "baseName": "Painter",
    "variant": "T1 Painter",
    "role": "Jungle",
    "rating": 56,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/T1_Painter.webp",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "frx-raptor",
    "baseName": "Raptor",
    "variant": "FRX Raptor",
    "role": "Jungle",
    "rating": 64,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/FRX_raptor.webp",
    "nationality": "KR",
    "teamTag": "FRX",
    "league": "LCK"
  },
  {
    "id": "t1-oner",
    "baseName": "Oner",
    "variant": "T1 Oner",
    "role": "Jungle",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/T1_oner.webp",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "oner-lck",
    "baseName": "Oner",
    "variant": "LCK 2022 Spring Champion",
    "role": "Jungle",
    "rating": 84,
    "rarity": "Épique",
    "image": "/cardsImg/others/Oner_blondie.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "DKC-sharvel",
    "baseName": "Sharvel",
    "variant": "DK.C Sharvel",
    "role": "Jungle",
    "rating": 68,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DKC_sharvel.webp",
    "nationality": "KR",
    "teamTag": "DK.C",
    "league": "LCK"
  },
  {
    "id": "hle-peanut",
    "baseName": "Peanut",
    "variant": "HLE Peanut",
    "role": "Jungle",
    "rating": 79,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/HLE_peanut.webp",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "peanut-lck-mvp",
    "baseName": "Peanut",
    "variant": "LCK MVP Peanut",
    "role": "Jungle",
    "rating": 86,
    "rarity": "Épique",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "C9-blaber",
    "baseName": "Blaber",
    "variant": "C9 Blaber",
    "role": "Jungle",
    "rating": 71,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/C9_blaber.webp",
    "nationality": "US",
    "teamTag": "C9",
    "league": "LCS"
  },
  {
    "id": "tes-tian",
    "baseName": "Tian",
    "variant": "TES Tian",
    "role": "Jungle",
    "rating": 80,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/TES_tian.webp",
    "nationality": "CN",
    "teamTag": "TES",
    "league": "LPL"
  },
  {
    "id": "tian-lpl-champ",
    "baseName": "Tian",
    "variant": "LPL Champion",
    "role": "Jungle",
    "rating": 85,
    "rarity": "Épique",
    "image": "/cardsImg/others/FPX_Tian_LPL.jpg",
    "nationality": "CN",
    "teamTag": "FPX",
    "league": "LPL"
  },
  {
    "id": "mad-elyoya",
    "baseName": "Elyoya",
    "variant": "MAD Lions Elyoya",
    "role": "Jungle",
    "rating": 77,
    "rarity": "Rare",
    "image": "/cardsImg/others/MAD_elyoya.png",
    "nationality": "ES",
    "teamTag": "MAD",
    "league": "LEC"
  },
  {
    "id": "th-sheo",
    "baseName": "Sheo",
    "variant": "TH Sheo",
    "role": "Jungle",
    "rating": 64,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/TH_sheo.webp",
    "nationality": "FR",
    "teamTag": "TH",
    "league": "LEC"
  },
  {
    "id": "kc-yike",
    "baseName": "Yike",
    "variant": "KC Yike",
    "role": "Jungle",
    "rating": 78,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/KC_yike.webp",
    "nationality": "SE",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "blg-xun",
    "baseName": "Xun",
    "variant": "BLG Xun",
    "role": "Jungle",
    "rating": 80,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/blg_xun.webp",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "vit-lyncas",
    "baseName": "Lyncas",
    "variant": "VIT Lyncas",
    "role": "Jungle",
    "rating": 66,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/VIT_lyncas.webp",
    "nationality": "LT",
    "teamTag": "VIT",
    "league": "LEC"
  },
  {
    "id": "g2-jankos",
    "baseName": "Jankos",
    "variant": "G2 Jankos",
    "role": "Jungle",
    "rating": 79,
    "rarity": "Rare",
    "image": "/cardsImg/others/G2_jankos.png",
    "nationality": "PL",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "th-daglas",
    "baseName": "Daglas",
    "variant": "TH Daglas",
    "role": "Jungle",
    "rating": 62,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/TH_daglas.webp",
    "nationality": "PL",
    "teamTag": "TH",
    "league": "LEC"
  },
  {
    "id": "fnc-razork",
    "baseName": "Razork",
    "variant": "FNC Razork",
    "role": "Jungle",
    "rating": 75,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/FNC_razork.webp",
    "nationality": "ES",
    "teamTag": "FNC",
    "league": "LEC"
  },

  // ==========================================
  // --- MIDLANE ---
  // ==========================================
  {
    "id": "sk-serin",
    "baseName": "Serin",
    "variant": "SK Serin",
    "role": "Mid",
    "rating": 59,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/SK_serin.webp",
    "nationality": "TR",
    "teamTag": "SK",
    "league": "LEC"
  },
  {
    "id": "faker-t1-2022",
    "baseName": "Faker",
    "variant": "T1 Faker",
    "role": "Mid",
    "rating": 85,
    "rarity": "Rare",
    "image": "/cardsImg/others/faker_T1.png",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "faker-6x-champ",
    "baseName": "Faker",
    "variant": "6x World Champion",
    "role": "Mid",
    "rating": 95,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/T1_faker.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "faker-hall-of-legends",
    "baseName": "Faker",
    "variant": "Unkillable Demon King",
    "role": "Mid",
    "rating": 99,
    "rarity": "WANTED",
    "image": "/cardsImg/others/faker_UDK2.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "nongshim-scout",
    "baseName": "Scout",
    "variant": "NS Scout",
    "role": "Mid",
    "rating": 73,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/NS_scout.webp",
    "nationality": "KR",
    "teamTag": "NS",
    "league": "LCK"
  },
  {
    "id": "chovy-geng-2023",
    "baseName": "Chovy",
    "variant": "Gen.G Chovy",
    "role": "Mid",
    "rating": 85,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/geng_chovy.webp",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "chovy-msi-2024",
    "baseName": "Chovy",
    "variant": "MSI Champion Chovy",
    "role": "Mid",
    "rating": 91,
    "rarity": "Épique",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "chovy-4peat",
    "baseName": "Chovy",
    "variant": "LCK 4PEAT",
    "role": "Mid",
    "rating": 93,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/GENG_chovy_leg.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "zeka-FST-mvp",
    "baseName": "Zeka",
    "variant": "First Stand MVP Zeka",
    "role": "Mid",
    "rating": 88,
    "rarity": "Épique",
    "image": "/cardsImg/others/FST_MVP_ZEKA.jpg",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "GX-jackies",
    "baseName": "Jackies",
    "variant": "GX Jackies",
    "role": "Mid",
    "rating": 69,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/GX_jackies.webp",
    "nationality": "CZ",
    "teamTag": "GX",
    "league": "LEC"
  },
  {
    "id": "showmaker-dk-2024",
    "baseName": "ShowMaker",
    "variant": "DK ShowMaker",
    "role": "Mid",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/dk_showmaker.webp",
    "nationality": "KR",
    "teamTag": "DK",
    "league": "LCK"
  },
  {
    "id": "showmaker-worlds-2020",
    "baseName": "ShowMaker",
    "variant": "2026 EWC ShowMaker",
    "role": "Mid",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/DK_2026_showmaker.jpg",
    "nationality": "KR",
    "teamTag": "DK",
    "league": "LCK"
  },
  {
    "id": "showmaker-prime",
    "baseName": "Showmaker",
    "variant": "THE MAGICIAN",
    "role": "Mid",
    "rating": 97,
    "rarity": "WANTED",
    "image": "/cardsImg/others/showmaker_prime.jpg",
    "nationality": "KR",
    "teamTag": "DWG",
    "league": "LCK"
  },
  {
    "id": "showmaker-DK-mentor",
    "baseName": "ShowMaker",
    "variant": "Mentor",
    "role": "Mid",
    "rating": 94,
    "rarity": "WANTED",
    "image": "/cardsImg/others/showmaker_mentor.jpg",
    "nationality": "KR",
    "teamTag": "DK",
    "league": "LCK"
  },
  {
    "id": "shifters-nuc",
    "baseName": "Nuc",
    "variant": "SHFT Nuc",
    "role": "Mid",
    "rating": 65,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/SHFT_nuc.webp",
    "nationality": "FR",
    "teamTag": "SHFT",
    "league": "LEC"
  },
  {
    "id": "knight-blg-2024",
    "baseName": "Knight",
    "variant": "BLG Knight",
    "role": "Mid",
    "rating": 85,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/blg_knight.webp",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "kc-kyeahoo-2026",
    "baseName": "Kyeahoo",
    "variant": "KC Kyeahoo",
    "role": "Mid",
    "rating": 75,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/kc_kyeahoo.webp",
    "nationality": "KR",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "knight-msi-2023",
    "baseName": "Knight",
    "variant": "FST Champion",
    "role": "Mid",
    "rating": 88,
    "rarity": "Épique",
    "image": "/cardsImg/others/FST_knight.jpg",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "knight-lpl-legend",
    "baseName": "Knight",
    "variant": "LPL Legend",
    "role": "Mid",
    "rating": 93,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/JDG_knight_msi.png",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "DRX_ucal",
    "baseName": "Ucal",
    "variant": "DRX Ucal",
    "role": "Mid",
    "rating": 69,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DRX_ucal.webp",
    "nationality": "KR",
    "teamTag": "DRX",
    "league": "LCK"
  },
  {
    "id": "rookie-ig",
    "baseName": "Rookie",
    "variant": "IG Rookie",
    "role": "Mid",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/IG_rookie.webp",
    "nationality": "KR",
    "teamTag": "IG",
    "league": "LPL"
  },
  {
    "id": "rookie-IG_2019",
    "baseName": "Rookie",
    "variant": "LPL Champion",
    "role": "Mid",
    "rating": 86,
    "rarity": "Épique",
    "image": "/cardsImg/others/IG_Rookie_2019.jpg",
    "nationality": "KR",
    "teamTag": "IG",
    "league": "LPL"
  },
  {
    "id": "fnc-vladi",
    "baseName": "Vladi",
    "variant": "FNC Vladi",
    "role": "Mid",
    "rating": 71,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/FNC_vladi.webp",
    "nationality": "CZ",
    "teamTag": "FNC",
    "league": "LEC"
  },
  {
    "id": "caps-g2-2024",
    "baseName": "Caps",
    "variant": "G2 Caps",
    "role": "Mid",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/g2_caps.webp",
    "nationality": "DK",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "caps-msi-mvp",
    "baseName": "Caps",
    "variant": "2019 MSI MVP",
    "role": "Mid",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/CAPS-MSI.avif",
    "nationality": "DK",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "FEARX-vicla",
    "baseName": "Vicla",
    "variant": "FRX Vicla",
    "role": "Mid",
    "rating": 70,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/FEARX_vicla.webp",
    "nationality": "KR",
    "teamTag": "FRX",
    "league": "LCK"
  },
  {
    "id": "nisqy-c9",
    "baseName": "Nisqy",
    "variant": "C9 Nisqy",
    "role": "Mid",
    "rating":78,
    "rarity": "Rare",
    "image": "/cardsImg/others/cloud9_nisqy.png",
    "nationality": "BE",
    "teamTag": "C9",
    "league": "LCS"

  },
  {
    "id": "navi_poby",
    "baseName": "Poby",
    "variant": "Navi Poby",
    "role": "Mid",
    "rating": 65,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/navi_poby.webp",
    "nationality": "KR",
    "teamTag": "NAVI",
    "league": "LEC"
  },
  {
    "id": "bdd-kt",
    "baseName": "Bdd",
    "variant": "KT Bdd",
    "role": "Mid",
    "rating": 80,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/KT_bdd.webp",
    "nationality": "KR",
    "teamTag": "KT",
    "league": "LCK"
  },
  {
    "id": "bdd-lck-mvp",
    "baseName": "Bdd",
    "variant": "2025 Worlds finalist",
    "role": "Mid",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/world_finalist_bdd_2025.jpg",
    "nationality": "KR",
    "teamTag": "KT",
    "league": "LCK"
  },
  {
    "id": "larssen-RGE",
    "baseName": "Larssen",
    "variant": "LEC Champion Larssen",
    "role": "Mid",
    "rating": 78,
    "rarity": "Rare",
    "image": "/cardsImg/others/larssen_lec_champ.png",
    "nationality": "SE",
    "teamTag": "RGE",
    "league": "LEC"
  },
  {
    "id": "BRO-roamer",
    "baseName": "Roamer",
    "variant": "BRO Roamer",
    "role": "Mid",
    "rating": 63,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/BRO_roamer.webp",
    "nationality": "KR",
    "teamTag": "BRO",
    "league": "LCK"
  },
  {
    "id": "DNS_clozer",
    "baseName": "Clozer",
    "variant": "DNS Clozer",
    "role": "Mid",
    "rating": 64,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DNS_clozer.webp",
    "nationality": "KR",
    "teamTag": "DNS",
    "league": "LCK"
  },

 // ==========================================
 // --- ADC ---
 // ==========================================
  {
    "id": "ruler-ssg",
    "baseName": "Ruler",
    "variant": "SSG Ruler",
    "role": "ADC",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/others/ssg_ruler.png",
    "nationality": "KR",
    "teamTag": "SSG",
    "league": "LCK"
  },
  {
    "id": "FLY-massu",
    "baseName": "Massu",
    "variant": "FLY Massu",
    "role": "ADC",
    "rating": 76,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/FLY_massu.webp",
    "nationality": "CA",
    "teamTag": "FLY",
    "league": "LCS"
  },
  {
    "id": "ruler-msi-2023",
    "baseName": "Ruler",
    "variant": "MSI Champion",
    "role": "ADC",
    "rating": 88,
    "rarity": "Épique",
    "image": "/cardsImg/others/jdg_ruler_msi.jpg",
    "nationality": "KR",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "ruler-worlds-mvp",
    "baseName": "Ruler",
    "variant": "Worlds MVP",
    "role": "ADC",
    "rating": 95,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/GENG_ruler.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "drx-jiwoo",
    "baseName": "Jiwoo",
    "variant": "DRX Jiwoo",
    "role": "ADC",
    "rating": 69,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DRX_jiwoo.webp",
    "nationality": "KR",
    "teamTag": "DRX",
    "league": "LCK"
  },
  {
    "id": "hle-viper",
    "baseName": "Viper",
    "variant": "HLE Viper",
    "role": "ADC",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/others/HLE_viper.png",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "blg-viper",
    "baseName": "Viper",
    "variant": "BLG Viper",
    "role": "ADC",
    "rating": 83,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/BLG_viper.webp",
    "nationality": "KR",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "viper-worlds-2021",
    "baseName": "Viper",
    "variant": "3x LPL champion",
    "role": "ADC",
    "rating": 88,
    "rarity": "Épique",
    "image": "/cardsImg/others/blg_viper_lpl.jpg",
    "nationality": "KR",
    "teamTag": "EDG",
    "league": "LPL"
  },
  {
    "id": "viper-lpl-mvp",
    "baseName": "Viper",
    "variant": "LPL MVP",
    "role": "ADC",
    "rating": 90,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/BLG_viper_leg.jpg",
    "nationality": "KR",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "bro-teddy",
    "baseName": "Teddy",
    "variant": "BRO Teddy",
    "role": "ADC",
    "rating": 70,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/BRO_teddy.webp",
    "nationality": "KR",
    "teamTag": "BRO",
    "league": "LCK"
  },
  {
    "id": "gumayusi-t1-2022",
    "baseName": "Gumayusi",
    "variant": "T1 Gumayusi",
    "role": "ADC",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/webp/t1_gumayusi.webp",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "gumayusi-T1-legend",
    "baseName": "Gumayusi",
    "variant": "T1 Legend",
    "role": "ADC",
    "rating": 93,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/T1_gumayusi.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "th-flakked",
    "baseName": "Flakked",
    "variant": "TH Flakked",
    "role": "ADC",
    "rating": 65,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/TH_flakked.webp",
    "nationality": "ES",
    "teamTag": "TH",
    "league": "LEC"
  },
  {
    "id": "blg-elk",
    "baseName": "Elk",
    "variant": "BLG Elk",
    "role": "ADC",
    "rating": 80,
    "rarity": "Rare",
    "image": "/cardsImg/others/BLG_elk.png",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "elk-lpl-mvp",
    "baseName": "Elk",
    "variant": "LPL MVP",
    "role": "ADC",
    "rating": 86,
    "rarity": "Épique",
    "image": "/cardsImg/others/elk_lpl_mvp.jpg",
    "nationality": "CN",
    "teamTag": "BLG",
    "league": "LPL"
  },
  {
    "id": "sen-rahel",
    "baseName": "Rahel",
    "variant": "EN Rahel",
    "role": "ADC",
    "rating": 61,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/SEN_rahel.webp",
    "nationality": "KR",
    "teamTag": "SEN",
    "league": "LCS"
  },
  {
    "id": "tes-jackeylove",
    "baseName": "JackeyLove",
    "variant": "TES JackeyLove",
    "role": "ADC",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/TES_jackeylove.webp",
    "nationality": "CN",
    "teamTag": "TES",
    "league": "LPL"
  },
  {
    "id": "DNS-deokdam",
    "baseName": "Deokdam",
    "variant": "DNS Deokdam",
    "role": "ADC",
    "rating": 67,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DNS_deokdam.webp",
    "nationality": "KR",
    "teamTag": "DNS",
    "league": "LCK"
  },
  {
    "id": "T1-peyz",
    "baseName": "Peyz",
    "variant": "T1 Peyz",
    "role": "ADC",
    "rating": 84,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/T1_peyz.webp",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "peyz-finals-mvp",
    "baseName": "Peyz",
    "variant": "LCK Finals MVP Peyz",
    "role": "ADC",
    "rating": 89,
    "rarity": "Épique",
    "image": "/cardsImg/others/peyz_lck_mvp.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "GenG-ruler",
    "baseName": "Ruler",
    "variant": "Gen.G Ruler",
    "role": "ADC",
    "rating": 82,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/GENG_ruler.webp",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "caliste-kcorp-2024",
    "baseName": "Caliste",
    "variant": "KC Caliste",
    "role": "ADC",
    "rating": 77,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/kc_caliste.webp",
    "nationality": "FR",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "caliste-2026",
    "baseName": "Caliste",
    "variant": "EWC 2026 Caliste",
    "role": "ADC",
    "rating": 86,
    "rarity": "Épique",
    "image": "/cardsImg/fullart/caliste_star.jpg",
    "nationality": "FR",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "caliste-prodige",
    "baseName": "Caliste",
    "variant": "Le Prodige",
    "role": "ADC",
    "rating": 89,
    "rarity": "WANTED",
    "image": "/cardsImg/others/caliste_prodigy.jpg",
    "nationality": "FR",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "th-ice",
    "baseName": "Ice",
    "variant": "TH Ice",
    "role": "ADC",
    "rating": 71,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/TH_ice.webp",
    "nationality": "KR",
    "teamTag": "TH",
    "league": "LEC"
  },
  {
    "id": "g2-hanssama",
    "baseName": "Hans Sama",
    "variant": "G2 Hans Sama",
    "role": "ADC",
    "rating": 79,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/G2_hans-sama.webp",
    "nationality": "FR",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "kc-upset",
    "baseName": "Upset",
    "variant": "KC Upset",
    "role": "ADC",
    "rating": 61,
    "rarity": "Commune",
    "image": "/cardsImg/others/KC_upset.png",
    "nationality": "DE",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "uzi-msi-2018",
    "baseName": "Uzi",
    "variant": "MSI MVP",
    "role": "ADC",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/uzi_msi.webp",
    "nationality": "CN",
    "teamTag": "RNG",
    "league": "LPL"
  },
  {
    "id": "uzi-adc-god",
    "baseName": "Uzi",
    "variant": "ADC God",
    "role": "ADC",
    "rating": 95,
    "rarity": "WANTED",
    "image": "/cardsImg/others/uzi_adc_god.png",
    "nationality": "CN",
    "teamTag": "RNG",
    "league": "LPL"
  },



  // ==========================================
  // --- SUPPORT ---
  // ==========================================
  {
    "id": "dns-peter",
    "baseName": "Peter",
    "variant": "DNS Peter",
    "role": "Support",
    "rating": 66,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/DNS_peter.webp",
    "nationality": "KR",
    "teamTag": "DNS",
    "league": "LCK"
  },
  {
    "id": "t1-keria",
    "baseName": "Keria",
    "variant": "T1 Keria",
    "role": "Support",
    "rating": 84,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/T1_keria.webp",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "keria-lck-mvp",
    "baseName": "Keria",
    "variant": "LCK MVP Keria",
    "role": "Support",
    "rating": 88,
    "rarity": "Épique",
    "image": "/cardsImg/others/T1_keria_2022.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "keria-worlds-2023",
    "baseName": "Keria",
    "variant": "World Champion",
    "role": "Support",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/T1_keria.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "keria-3PEAT-WC",
    "baseName": "Keria",
    "variant": "3PEAT Worlds",
    "role": "Support",
    "rating": 97,
    "rarity": "WANTED",
    "image": "/cardsImg/others/3PEAT_keria.jpg",
    "nationality": "KR",
    "teamTag": "T1",
    "league": "LCK"
  },
  {
    "id": "kt-effort",
    "baseName": "Effort",
    "variant": "KT Effort",
    "role": "Support",
    "rating": 71,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/KT_effort.webp",
    "nationality": "KR",
    "teamTag": "KT",
    "league": "LCK"
  },
  {
    "id": "jdg-missing",
    "baseName": "MISSING",
    "variant": "JDG MISSING",
    "role": "Support",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/others/JDG_missing.png",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "3LPL-missing",
    "baseName": "Missing",
    "variant": "3x LPL champion Missing",
    "role": "Support",
    "rating": 85,
    "rarity": 'Épique',
    "image": "/cardsImg/others/JDG_missing.jpg",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "missing-msi-2023",
    "baseName": "Missing",
    "variant": "MSI Champion Missing",
    "role": "Support",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/MSI_MISSING.jpeg",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  },
  {
    "id": "gx-jun",
    "baseName": "Jun",
    "variant": "GX Jun",
    "role": "Support",
    "rating": 65,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/GX_jun.webp",
    "nationality": "KR",
    "teamTag": "GX",
    "league": "LEC"
  },
  {
    "id": "hle-delight",
    "baseName": "Delight",
    "variant": "HLE Delight",
    "role": "Support",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/HLE_delight.webp",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "delight-hle-2024",
    "baseName": "Delight",
    "variant": "2025 First Stand Champion",
    "role": "Support",
    "rating": 85,
    "rarity": "Épique",
    "image": "/cardsImg/others/delight_firststand_2025.jpg",
    "nationality": "KR",
    "teamTag": "HLE",
    "league": "LCK"
  },
  {
    "id": "th-way",
    "baseName": "Way",
    "variant": "TH Way",
    "role": "Support",
    "rating": 60,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/TH_way.webp",
    "nationality": "KR",
    "teamTag": "TH",
    "league": "LEC"
  },
  {
    "id": "ns-lehends",
    "baseName": "Lehends",
    "variant": "NS Lehends",
    "role": "Support",
    "rating": 74,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/NS_lehends.webp",
    "nationality": "KR",
    "teamTag": "NS",
    "league": "LCK"
  },
  {
    "id": "lehends-lck-2x",
    "baseName": "Lehends",
    "variant": "2x LCK champion",
    "role": "Support",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/lck_lehends_geng.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "lehends-msi_mvp",
    "baseName": "Lehends",
    "variant": "2024 MSI MVP",
    "role": "Support",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/msi_mvp_lehends.jpg",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "sk-mikyx",
    "baseName": "Mikyx",
    "variant": "SK Mikyx",
    "role": "Support",
    "rating": 63,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/SK_mikyx.webp",
    "nationality": "SI",
    "teamTag": "SK",
    "league": "LEC"
  },
  {
    "id": "geng-duro",
    "baseName": "Duro",
    "variant": "Gen.G Duro",
    "role": "Support",
    "rating": 84,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/GENG_duro.webp",
    "nationality": "KR",
    "teamTag": "GEN",
    "league": "LCK"
  },
  {
    "id": "mikyx-msi-2019",
    "baseName": "Mikyx",
    "variant": "MSI Champion Mikyx",
    "role": "Support",
    "rating": 86,
    "rarity": "Épique",
    "image": "/cardsImg/others/MSI_2019_mikyx.jpg",
    "nationality": "SI",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "th-stend",
    "baseName": "Stend",
    "variant": "TH Stend",
    "role": "Support",
    "rating": 58,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/TH_stend.webp",
    "nationality": "FR",
    "teamTag": "TH",
    "league": "LEC"
  },
  {
    "id": "kc-targamas",
    "baseName": "Targamas",
    "variant": "KC Targamas",
    "role": "Support",
    "rating": 76,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/KC_targamas.webp",
    "nationality": "BE",
    "teamTag": "KC",
    "league": "LEC"
  },
  {
    "id": "g2-labrov",
    "baseName": "Labrov",
    "variant": "G2 Labrov",
    "role": "Support",
    "rating": 80,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/G2_labrov.webp",
    "nationality": "GR",
    "teamTag": "G2",
    "league": "LEC"
  },
  {
    "id": "vit-hylissang",
    "baseName": "Hylissang",
    "variant": "VIT Hylissang",
    "role": "Support",
    "rating": 55,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/VIT_hylissang.webp",
    "nationality": "BG",
    "teamTag": "VIT",
    "league": "LEC"
  },
  {
    "id": "mdk-alvaro",
    "baseName": "Alvaro",
    "variant": "MDK Alvaro",
    "role": "Support",
    "rating": 69,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/MDK_alvaro.webp",
    "nationality": "ES",
    "teamTag": "MDK",
    "league": "LEC"
  },
  {
    "id": "tl-corejj",
    "baseName": "CoreJJ",
    "variant": "TL CoreJJ",
    "role": "Support",
    "rating": 76,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/TL_corejj.webp",
    "nationality": "KR",
    "teamTag": "TL",
    "league": "LCS"
  },
  {
    "id": "frx-kellin",
    "baseName": "Kellin",
    "variant": "FRX Kellin",
    "role": "Support",
    "rating": 67,
    "rarity": "Commune",
    "image": "/cardsImg/2026-players/FRX_kellin.webp",
    "nationality": "KR",
    "teamTag": "FRX",
    "league": "LCK"
  },
  {
    "id": "meiko-tes",
    "baseName": "Meiko",
    "variant": "TES Meiko",
    "role": "Support",
    "rating": 81,
    "rarity": "Rare",
    "image": "/cardsImg/others/tes_meiko.png",
    "nationality": "CN",
    "teamTag": "TES",
    "league": "LPL"
  },
  {
    "id": "meiko-edg-msi",
    "baseName": "Meiko",
    "variant": "MSI Champion Meiko",
    "role": "Support",
    "rating": 87,
    "rarity": "Épique",
    "image": "/cardsImg/others/EDG_meiko_MSI.png",
    "nationality": "CN",
    "teamTag": "EDG",
    "league": "LPL"
  },
  {
    "id": "meiko-LPL-Legend",
    "baseName": "Meiko",
    "variant": "LPL Legend",
    "role": "Support",
    "rating": 92,
    "rarity": "Légendaire",
    "image": "/cardsImg/others/legend_MEIKO.jpg",
    "nationality": "CN",
    "teamTag": "EDG",
    "league": "LPL"
  },
  {
    "id": "JDG-2026-vampire",
    "baseName": "Vampire",
    "variant": "JDG Vampire",
    "role": "Support",
    "rating": 78,
    "rarity": "Rare",
    "image": "/cardsImg/2026-players/JDG_vampire.webp",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  },


  /////// SPECIAL ///////

  {
    "id": "ruler-missing-redemption",
    "baseName": "JDG 2023 Missing",
    "variant": "La Rédemption",
    "role": "Support", 
    "rating": 96,
    "themeColor": '#E5142E',
    "rarity": "SECRET", 
    "image": "/cardsImg/others/ruler_missing_DUO.jpg",
    "nationality": "CN",
    "teamTag": "JDG",
    "league": "LPL"
  }
];