export const PRO_PLAYERS = [
  // Top
  { id: 'zeus', name: 'Zeus', role: 'Top', rating: 96 }, { id: 'bin', name: 'Bin', role: 'Top', rating: 95 }, { id: '369', name: '369', role: 'Top', rating: 93 }, { id: 'kiin', name: 'Kiin', role: 'Top', rating: 92 }, { id: 'brokenblade', name: 'BrokenBlade', role: 'Top', rating: 85 }, { id: 'adam', name: 'Adam', role: 'Top', rating: 82 }, { id: 'impact', name: 'Impact', role: 'Top', rating: 84 }, { id: 'doran', name: 'Doran', role: 'Top', rating: 88 }, { id: 'wunder', name: 'Wunder', role: 'Top', rating: 80 },{ id: 'theshy', name: 'TheShy', role: 'Top', rating: 95 }, { id: 'smeb', name: 'Smeb', role: 'Top', rating: 94 }, { id: 'khan', name: 'Khan', role: 'Top', rating: 93 }, { id: 'marin', name: 'MaRin', role: 'Top', rating: 93 }, { id: 'nuguri', name: 'Nuguri', role: 'Top', rating: 92 },
  // Jungle
  { id: 'canyon', name: 'Canyon', role: 'Jungle', rating: 97 }, { id: 'kanavi', name: 'Kanavi', role: 'Jungle', rating: 95 }, { id: 'oner', name: 'Oner', role: 'Jungle', rating: 92 }, { id: 'peanut', name: 'Peanut', role: 'Jungle', rating: 90 }, { id: 'tian', name: 'Tian', role: 'Jungle', rating: 88 }, { id: 'elyoya', name: 'Elyoya', role: 'Jungle', rating: 86 }, { id: 'yike', name: 'Yike', role: 'Jungle', rating: 84 }, { id: 'jankos', name: 'Jankos', role: 'Jungle', rating: 85 }, { id: 'razork', name: 'Razork', role: 'Jungle', rating: 87 },{ id: 'bengi', name: 'Bengi', role: 'Jungle', rating: 94 }, { id: 'score', name: 'Score', role: 'Jungle', rating: 93 }, { id: 'dandy', name: 'DanDy', role: 'Jungle', rating: 93 }, { id: 'ambition', name: 'Ambition', role: 'Jungle', rating: 92 }, { id: 'clearlove', name: 'Clearlove', role: 'Jungle', rating: 91 }, { id: 'tarzan', name: 'Tarzan', role: 'Jungle', rating: 90 },
  // Mid
  { id: 'faker', name: 'Faker', role: 'Mid', rating: 98 }, { id: 'chovy', name: 'Chovy', role: 'Mid', rating: 99 }, { id: 'showmaker', name: 'ShowMaker', role: 'Mid', rating: 93 }, { id: 'knight', name: 'Knight', role: 'Mid', rating: 95 }, { id: 'rookie', name: 'Rookie', role: 'Mid', rating: 91 }, { id: 'caps', name: 'Caps', role: 'Mid', rating: 89 }, { id: 'nisqy', name: 'Nisqy', role: 'Mid', rating: 82 }, { id: 'bdd', name: 'Bdd', role: 'Mid', rating: 88 }, { id: 'larssen', name: 'Larssen', role: 'Mid', rating: 84 },{ id: 'scout', name: 'Scout', role: 'Mid', rating: 94 }, { id: 'xiaohu', name: 'Xiaohu', role: 'Mid', rating: 94 }, { id: 'doinb', name: 'Doinb', role: 'Mid', rating: 92 }, { id: 'pawn', name: 'Pawn', role: 'Mid', rating: 91 }, { id: 'perkz', name: 'Perkz', role: 'Mid', rating: 90 },
  // ADC
  { id: 'ruler', name: 'Ruler', role: 'ADC', rating: 97 }, { id: 'viper', name: 'Viper', role: 'ADC', rating: 96 }, { id: 'gumayusi', name: 'Gumayusi', role: 'ADC', rating: 94 }, { id: 'elk', name: 'Elk', role: 'ADC', rating: 92 }, { id: 'jackeylove', name: 'JackeyLove', role: 'ADC', rating: 90 }, { id: 'peyz', name: 'Peyz', role: 'ADC', rating: 89 }, { id: 'caliste', name: 'Caliste', role: 'ADC', rating: 86 }, { id: 'hanssama', name: 'Hans Sama', role: 'ADC', rating: 85 }, { id: 'upset', name: 'Upset', role: 'ADC', rating: 83 },{ id: 'uzi', name: 'Uzi', role: 'ADC', rating: 96 }, { id: 'deft', name: 'Deft', role: 'ADC', rating: 95 }, { id: 'bang', name: 'Bang', role: 'ADC', rating: 93 }, { id: 'pray', name: 'PraY', role: 'ADC', rating: 92 }, { id: 'rekkles', name: 'Rekkles', role: 'ADC', rating: 90 },
  // Support
  { id: 'keria', name: 'Keria', role: 'Support', rating: 98 }, { id: 'missing', name: 'Missing', role: 'Support', rating: 93 }, { id: 'delight', name: 'Delight', role: 'Support', rating: 91 }, { id: 'lehends', name: 'Lehends', role: 'Support', rating: 92 }, { id: 'mikyx', name: 'Mikyx', role: 'Support', rating: 88 }, { id: 'targamas', name: 'Targamas', role: 'Support', rating: 80 }, { id: 'hylissang', name: 'Hylissang', role: 'Support', rating: 82 }, { id: 'corejj', name: 'CoreJJ', role: 'Support', rating: 85 }, { id: 'meiko', name: 'Meiko', role: 'Support', rating: 94 }, { id: 'mata', name: 'Mata', role: 'Support', rating: 96 }, { id: 'beryl', name: 'BeryL', role: 'Support', rating: 94 }, { id: 'madlife', name: 'MadLife', role: 'Support', rating: 94 }, { id: 'ming', name: 'Ming', role: 'Support', rating: 93 }, { id: 'wolf', name: 'Wolf', role: 'Support', rating: 92 }, { id: 'gorilla', name: 'GorillA', role: 'Support', rating: 91 }, { id: 'crisp', name: 'Crisp', role: 'Support', rating: 91 }
];