// src/constants/teams.js
export const TEAMS_DB = [
  { name: "Anyone's Legend", tag: "AL", logo: "/equipes/anyone-legend.webp" },
  { name: "Bilibili Gaming", tag: "BLG", logo: "/equipes/bilibili-gaming.webp" },
  { name: "BRION", tag: "BRO", logo: "/equipes/brion.webp" },
  { name: "Cloud9", tag: "C9", logo: "/equipes/cloud9.webp" },
  { name: "Dignitas", tag: "DIG", logo: "/equipes/dignitas.webp" },
  { name: "Disguised", tag: "DSG", logo: "/equipes/disguised.webp" },
  { name: "Dplus KIA", tag: "DK", logo: "/equipes/dplus.webp" },
  { name: "DRX", tag: "DRX", logo: "/equipes/drx.webp" },
  { name: "Damwon Gaming", tag: "DWG", logo: "/equipes/DWG.webp" },
  { name: "Edward Gaming", tag: "EDG", logo: "/equipes/edward-gaming.webp" },
  { name: "FearX", tag: "FOX", logo: "/equipes/fearx.webp" },
  { name: "FlyQuest", tag: "FLY", logo: "/equipes/flyquest.webp" },
  { name: "Fnatic", tag: "FNC", logo: "/equipes/fnatic.webp" },
  { name: "FunPlus Pheonix", tag: "FPX", logo: "equipes/funplus-phoenix.webp" },
  { name: "G2 Esports", tag: "G2", logo: "/equipes/g2.webp" },
  { name: "Gen.G", tag: "GEN", logo: "/equipes/geng.webp" },
  { name: "GiantX", tag: "GX", logo: "/equipes/giantx.webp" },
  { name: "Hanwha Life Esports", tag: "HLE", logo: "/equipes/hle.webp" },
  { name: "Invictus Gaming", tag: "IG", logo: "/equipes/invictus-gaming.webp" },
  { name: "JD Gaming", tag: "JDG", logo: "/equipes/jd-gaming.webp" },
  { name: "Karmine Corp", tag: "KC", logo: "/equipes/kc.webp" },
  { name: "KT Rolster", tag: "KT", logo: "/equipes/kt-rolster.webp" },
  { name: "LGD Gaming", tag: "LGD", logo: "/equipes/lgd-gaming.webp" },
  { name: "LNG Esports", tag: "LNG", logo: "/equipes/lng.webp" },
  { name: "Lunary", tag: "LNY", logo: "/equipes/lunary.webp" },
  { name: "Lyon Gaming", tag: "LYN", logo: "/equipes/lyon.webp" },
  { name: "Movistar KOI", tag: "MKOI", logo: "/equipes/mkoi.webp" },
  { name: "NAVI", tag: "NAVI", logo: "/equipes/navi.webp" },
  { name: "Ninjas in Pyjamas", tag: "NIP", logo: "/equipes/nip.webp" },
  { name: "Nongshim RedForce", tag: "NS", logo: "/equipes/nongshim.webp" },
  { name: "OMG", tag: "OMG", logo: "/equipes/omg.webp" },
  { name: "RNG", tag: "RNG", logo: "/equipes/royal-never-give-up.webp" },
  { name: "Sentinels", tag: "SEN", logo: "/equipes/sentinels.webp" },
  { name: "Shifters", tag: "SHF", logo: "/equipes/shifters.webp" },
  { name: "Shopify Rebellion", tag: "SR", logo: "/equipes/shopify-rebellion.webp" },
  { name: "SK Gaming", tag: "SK", logo: "/equipes/sk.webp" },
  { name: "Solary", tag: "SLY", logo: "/equipes/solary.webp" },
  { name: "Soopers", tag: "SPR", logo: "/equipes/soopers.webp" },
  { name: "T1", tag: "T1", logo: "/equipes/t1.webp" },
  { name: "Team Heretics", tag: "TH", logo: "/equipes/team-heretics.webp" },
  { name: "Team Liquid", tag: "TL", logo: "/equipes/team-liquid.webp" },
  { name: "ThunderTalk Gaming", tag: "TT", logo: "/equipes/thundertalk.webp" },
  { name: "Top Esports", tag: "TES", logo: "/equipes/top-esports.webp" },
  { name: "Team Vitality", tag: "VIT", logo: "/equipes/vitality.webp" },
  { name: "Team WE", tag: "WE", logo: "/equipes/we.webp" },
  { name: "Weibo Gaming", tag: "WBG", logo: "/equipes/weibo.webp" },
  { name: "ZyB", tag: "ZYB", logo: "/equipes/zyb.webp" }
];